import '../globals.css'
import { Inter } from 'next/font/google'
import Script from 'next/script'
import Head from 'next/head'
import Navbar from '../components/Navbar'
import Provider from '../components/context/Provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Realtime Pembayaran SPP',
  description: 'Generated by M Aqmal H',
  icons: {
    icon: '/favicon.ico',
  },
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
    

      </Head>
      <body className={inter.className}>
        <Navbar /> 
        <Provider>
          
        {children}
          </Provider> 
       <Script src='https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js' />
      </body>
    </html>
  )
}
